/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @Summary
 * 			This lab was pretty fun, I was able to get the task attribute and
 * 			SysTick handler for assembly files to work. This is my
 * 			first time ever working with assembly code but
 * 			though the help of google and StackoverFlow I was able to get a
 * 			sense of what is happening with my the assembly file. It also did
 * 			help that I stepped through each line in the assembly file and
 * 			open up the register view  in cube to visually see what each
 * 			command is doing. Unfortunately, I forgot to add .section .data
 * 			for my global variable task which caused the mcu to do some
 * 			unexpected commands and go to the infinite loop.
 * 			After adding that command and others such as .syntax unified and
 * 			thumb the code was working will. Some of other issues I had was
 * 			using ODR register instead of the BSRR register for doing my rmw
 * 			of the leds. Since BSRR is always atomic I can verify that no
 * 			interrupt will be run as I am doing these modifications.
 * 			Some differences that I noticed with using the task switcher is
 * 			that a very little lag with my console application and also the
 * 			led lights and the code looked more fluid than before.
 *
 *
 *@DatasheetNotes
 *			Interrupts are asynchronous events that disrupt the normal flow
 *			of your program. Allows MCY to focus on a key task and attend to
 *			the events as they come and needed.
 *
 *			To setup an interrupt on the F411 Board
 *			1. Configure the peripheral and enable the interrupt in the
 *				peripheral.
 *			2. Take note of the position and name of the interrupt on Table 37
 *				from chapter 10 of the technical reference manual.
 *				The position is the IRQn and the acronym is the predefined
 *				function ISR.
 *			3. Set the interrupt priority by writing on the interrupt priority
 *				register NVIC->IP
 *			4. Enable the interrupt itself by setting the
 *				appropriate NVIC->ISER bit. The value in which you
 *				should activate your value is based on the position value.
 *				  NVIC->ISER[IRQn >> 5] |= (1 << (IRQn % 32).
 *			5. Define your interrupt handler or ISR in your main.
 *
 ******************************************************************************
 */

//Note looks like the Piezo speaker is connected to PB4

#include <stdint.h>
#include "stdio.h"
#include "system.h"
#include "music.h"
#include "console.h"
#include "uart_driver.h"
#include "measure.h"
#include "WaveForm.h"
#include "delay.h"
#include "led.h"


//in pcb.s
extern uint32_t task[3];
#define STACK_SIZE 200

// stack for other task - STACK_SIZE words
uint32_t otherstack[STACK_SIZE];

void othertask( void );


int main(void)
{
	//UART2 for 57600
	init_usart2(57600, F_CPU);
	TIM2_init();
	TIM3_init();
	char data[MAX_LENGTH];
	ADC12_IN9_init();
	delay_int();
	led_init();
	led_allOff();
	//led_allOn();

	// have to establish stack for "other" task, and fille it in
	// with initial values, including return addres to task
	// entry point
	otherstack[STACK_SIZE-1] = 0x01000000; //PSR - a thumb state bit set
	otherstack[STACK_SIZE-2] = (uint32_t)othertask; //PC
	otherstack[STACK_SIZE-3] = 0xFFFFFFFF; //LR
	otherstack[STACK_SIZE-4] = 0; //R12
	otherstack[STACK_SIZE-5] = 0; //R3
	otherstack[STACK_SIZE-6] = 0; //R2
	otherstack[STACK_SIZE-7] = 0; //R1
	otherstack[STACK_SIZE-8] = 0; //R0
	otherstack[STACK_SIZE-9] = 0xFFFFFFF9; //LR stacked in ISR
	otherstack[STACK_SIZE-10] = 0; //R11
	otherstack[STACK_SIZE-11] = 0; //R10
	otherstack[STACK_SIZE-12] = 0; //R9
	otherstack[STACK_SIZE-13] = 0; //R8
	otherstack[STACK_SIZE-14] = 0; //R7
	otherstack[STACK_SIZE-15] = 0; //R6
	otherstack[STACK_SIZE-16] = 0; //R5
	otherstack[STACK_SIZE-17] = 0; //R4
	//put this position into task 1's stack pointer location
	task[1] = (uint32_t)(&otherstack[STACK_SIZE-17] );



	while(1)
	{

		//polling to check if the music has finished
		if( !Music_status() )
		{
			//if music has finished notify that the user tha music is done
			printf("Music has finished playing\n");
			printf("Play MUSIC AGAIN: \n");
		}


		//if the music is still playing
		printf("Enter your CMD: \n");
		fgets(data,MAX_LENGTH,stdin); //input from stdin stream
		printf("%s \n", data);
		Read_Text(data);

	}

}

void othertask( void )
{
	led_ride();
}
