/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @Summary
 * 			This lab was pretty fun, I was able to setup my adc converter to
 * 			work with the Timer4 and get it accurately working based on the
 * 			user selected sampling rate. One of the things That I really
 * 			struggled in was calculated the ARR value for the sampling rate
 * 			and attempting to get negative voltage values from the ADC.
 * 			After about 1-2 hours at attempting different alignment modes and
 * 			coding functions I was unable to get negative voltage showing when
 * 			running the getwave function but instead I just decided to offset
 * 			my signal so that it will only be a positive voltage regardless.
 * 			calloc and Free functions for dynamic memory was pretty easy to use
 * 			and get it working. Not alot of issues with that functionality of
 * 			code.
 *
 *
 *@DatasheetNotes
 *			Interrupts are asynchronous events that disrupt the normal flow
 *			of your program. Allows MCY to focus on a key task and attend to
 *			the events as they come and needed.
 *
 *			To setup an interrupt on the F411 Board
 *			1. Configure the peripheral and enable the interrupt in the
 *				peripheral.
 *			2. Take note of the position and name of the interrupt on Table 37
 *				from chapter 10 of the technical reference manual.
 *				The position is the IRQn and the acronym is the predefined
 *				function ISR.
 *			3. Set the interrupt priority by writing on the interrupt priority
 *				register NVIC->IP
 *			4. Enable the interrupt itself by setting the
 *				appropriate NVIC->ISER bit. The value in which you
 *				should activate your value is based on the position value.
 *				  NVIC->ISER[IRQn >> 5] |= (1 << (IRQn % 32).
 *			5. Define your interrupt handler or ISR in your main.
 *
 ******************************************************************************
 */

//Note looks like the Piezo speaker is connected to PB4

#include <stdint.h>
#include "stdio.h"
#include "system.h"
#include "music.h"
#include "console.h"
#include "uart_driver.h"
#include "measure.h"
#include "WaveForm.h"



int main(void)
{
	init_usart2(57600, F_CPU);
	TIM2_init();
	TIM3_init();
	char data[MAX_LENGTH];
	ADC12_IN9_init();

	while(1)
	{

		//polling to check if the music has finished
		if( !Music_status() )
		{
			//if music has finished notify that the user tha music is done
			printf("Music has finished playing\n");
			printf("Play MUSIC AGAIN: \n");
		}


		//if the music is still playing
		printf("Enter your CMD: \n");
		fgets(data,MAX_LENGTH,stdin); //input from stdin stream
		printf("%s \n", data);
		Read_Text(data);

	}
}


