/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @Summary
 * 			For this lab a console application was written that offers basic
 * 			system control such as reading, writing words to address. As well
 * 			as dumping memory of address that the user envokes. This lab was a
 * 			bit difficult to work at the start mostly just parsing the user
 * 			input string. At first I was simple using scanf() but that caused
 * 			alot of issues by creating unexpected behaviors when attemping to
 * 			pase the cmd variables. This is where sscanf() come to save the day.
 * 			This function allows me to break down a string into different other
 * 			subsets of strings based on their format. Which was done in my
 * 			Read_Text() function. Once variables are sections off I do did a
 * 			simple if-nested logic for checking what the string value cmd is.
 * 			Overall this lab was an alright and engaging lab but I really
 * 			learned alot of more with some critical flaws of strings in c and
 * 			the use of them. Such as if a program is not done correct hacking
 * 			of a project can be done such as buffer overflows, and strcpy to
 * 			name a few. Like when asking users for their login information or
 * 			credit card information.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "uart_driver.h"
#include "stdio.h"
#include "Console.h"

#define F_CPU 16000000UL


int main(void)
{
	init_usart2(57600,F_CPU);

	char data[MAX_LENGTH];
    /* Loop forever */
	for(;;)
	{
		printf("Enter your CMD: \n");
		fgets(data,MAX_LENGTH,stdin); //input from stdin stream
		printf("%s \n", data);
		Read_Text(data);
	}
}
