/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @Summary
 * 			This lab was pretty fun, the initlaizing of the GPIO pins and
 * 			generating the PWM was simple and easy to do once reading the
 * 			reference manual. For the number of ticks relating to frequency I
 * 			simply reference the lab report and created a simple equation.
 * 			I also was able calculate the higher octaves based on a simple bit
 * 			shifting equation for the notes ranges from A-G. One of the most
 * 			time consuming parts was the generation of the music sheet and
 * 			solving the issue I orginally had of my code going into a system
 * 			handler due to the use of floating point in my project not being
 * 			enabled. Luckily with the help of Dr.Rothe I was able to figure out
 * 			how to enable floating points and my issue was easily resolved.
 * 			Overall this was definitely one of the most interesting labs and
 * 			most enjoyable so far.
 *
 *
 ******************************************************************************
 */

//Note looks like the Piezo speaker is connected to PB4

#include <stdint.h>
#include "stdio.h"
#include "system.h"
#include "music.h"
#include "delay.h"
#include "Sheet_music.h"
//#include "led.h"
#include "uart_driver.h"

#define F_CPU 16000000UL

int main(void)
{
	init_usart2(57600, F_CPU);
	TIM3_init();

	int song_selection = 0;
	int tempo = 0;
	int size = 0;
	sTone *(music_pointer);
	while(1)
	{
		int play = 1;
		printf("Song Selection:\n");
		printf("1 - Scale\n");
		printf("2 - SuperMarioBros\n");
		printf("3 - A Thousands Years\n");
		printf("4 - O' Christmas Tree\n");
		scanf("%d", &song_selection);
		switch( song_selection)
		{
		case 1:
			//a pointer to an array of structures? What should I do with this?
			music_pointer = (sTone*) SCALE;
			tempo = 220;
			size = (sizeof(SCALE)/3);
			break;
		case 2:
			//a pointer to an array of structures? What should I do with this?
			music_pointer = (sTone*) Mario;
			tempo = 190;
			size = (sizeof(Mario)/3);
			break;
		case 3:
			//a pointer to an array of structures? What should I do with this?
			music_pointer = (sTone*) A_Thousand_Years;
			tempo = 100;
			size = (sizeof(A_Thousand_Years)/3);
			break;
		case 4:
			//a pointer to an array of structures? What should I do with this?
			music_pointer = (sTone*) ChristmasTree;
			tempo = 85;
			size = (sizeof(ChristmasTree)/3);
			break;
		default:
			printf("Error User has picked a song that doesnt exist\n"
					"plz try again\n");
			play = 0;
		}

		if( play > 0)
		{
			//calculate the notes delays
			temp_setup(tempo);
			play_music( music_pointer, size);
		}
	}
}
