/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
  * Summary of Experience:
  *    This lab was a was pretty fun when implementing. The most difficulty I
  *    had was initing the LCD screen from my LCD_init function. But after
  *    re-reading the data sheet and validating that my #define CMD were
  *    accurate the LCD was properly initalized. Afterwards, I have some issues
  *    with sending cmd data and at first I though it had to due with Pins not
  *    being set properly. But after double checking my input signals on the LCD
  *    screen I was able to verify that the GPIO were not the issues. The main
  *    issue I later figured out was my delays with each function. I originally,
  *    had the delays set to be at 100 ms. and not 37 us. This caused alot of
  *    issues in my sending of commands and once fixed was able to get the lcd
  *    working. Overall it was a fun experience and fun to redo the knight rider
  *    functionality.
  *
  *
  *
  *
  ******************************************************************************
*/


#include <stdio.h>
#include <stdlib.h>
//#include "uart_driver.h"
#include "delay.h"
#include "lcd.h"

#define ARSIZE 10
#define F_CPU 16000000UL

int main( void )
{
	//init_usart2( 57600, F_CPU );
	LCD_Init();
	LCD_Clear();
	LCD_Home();

	const char *d = "CE2801, CE2820, EE4930";
	LCD_Print_String(d, 0, 0);


	LCD_Set_Position(1,8);
	LCD_Print_num(28);
	delay_sec(1);

	const char light = '#';
	const char whitespace = ' ';
	LCD_Clear();

	while(1)
	{

			//counting upwards
			for( int j = 1; j < 16; j++)
			{
				LCD_Set_Position(0, j);
				LCD_Print_Char( light );
				LCD_Set_Position(1, j);
				LCD_Print_Char( light );
				delay_ms(25);

				LCD_Set_Position(0, j);
				LCD_Print_Char( whitespace );
				LCD_Set_Position(1, j);
				LCD_Print_Char( whitespace );



			}

			//counting downwards
			for( int j = 16; j >= 0; j--)
			{

				LCD_Set_Position(0, j);
				LCD_Print_Char( light );
				LCD_Set_Position(1, j);
				LCD_Print_Char( light );
				delay_ms(25);

				LCD_Set_Position(0, j);
				LCD_Print_Char( whitespace );
				LCD_Set_Position(1, j);
				LCD_Print_Char( whitespace );

			}

	}

}
