/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @Summary
 * 			This lab was pretty fun, I was able to get the interrupt intiliazed
 * 			and working with ease but was having alot of trouble of calculating
 * 			delay between each note. If my BPM was too high sometimes the notes
 * 			would not play due to the number of counter of being off. But after
 * 			playing around with the values and making sure i set all my file
 * 			scale variables too zero after use. The program worked well. Some
 * 			things that I would change if I had more time would be the way
 * 			I wrote the program and its executions. Ideally, I would like to
 * 			eliminate the amount file scope variables I used and reduce the code
 * 			size in main. I would also would like to figure out how to calculate
 * 			the delay amount so that the song would sound the same as lab5
 * 			instead of a slowed down version for this lab. Overall, I learned
 * 			alot and really enjoyed reading data sheets and setting up the timer
 * 			with interrupts.
 *
 *
 *@DatasheetNotes
 *			Interrupts are asynchronous events that distrupt the normal flow
 *			of your program. Allows MCY to focus on a key task and attend to
 *			the events as they come and needed.
 *
 *			To setup an interrupt on the F411 Board
 *			1. Configure the peripheral and enable the interrupt in the
 *				peripheral.
 *			2. Take note of the position and name of the interrupt on Table 37
 *				from chapter 10 of the technical reference manual. The position
 *				is the IRQn and the acronym  is the predefined  function ISR.
 *			3. Set the interrupt priority by writing on the interrupt priority
 *				register NVIC->IP
 *			4. Enable the interrupt itself by setting the appropriate NVIC->ISER
 *				bit. The value in which you should activate your value is based
 *				on the position value.
 *				  NVIC->ISER[IRQn >> 5] |= (1 << (IRQn % 32).
 *			5. Define your interrupt handler or ISR in your main function code.
 *
 ******************************************************************************
 */

//Note looks like the Piezo speaker is connected to PB4

#include <stdint.h>
#include "stdio.h"
#include "system.h"
#include "music.h"
#include "delay.h"
#include "Sheet_music.h"
#include "led.h"
#include "console.h"
#include "uart_driver.h"

#define F_CPU 16000000UL


int main(void)
{
	init_usart2(57600, F_CPU);
	TIM3_init();
	char data[MAX_LENGTH];
	int again = 0;
	while(1)
	{
		//polling to check if the music has finished
		if( !Music_status() )
		{
			//if music has finished notify that the user tha music is done
			printf("Music has finished playing\n");
			printf("Play MUSIC AGAIN: \n");
			again = 1;
		}
		else
		{
			//if the music is still playing
			printf("Enter your CMD: \n");
			fgets(data,MAX_LENGTH,stdin); //input from stdin stream
			printf("%s \n", data);
			Read_Text(data);
		}

		if( again )
		{
			//if the music is still playing
			printf("Enter your CMD: \n");
			fgets(data,MAX_LENGTH,stdin); //input from stdin stream
			printf("%s \n", data);
			Read_Text(data);
			again = 0;
		}
	} //end of while loop
}


